:defaults: &defaults
  :host: localhost
  :allow_dynamic_fields: false
  :parameterize_keys: false
  :persist_in_safe_mode: false
  :raise_not_found_error: false
  :reconnect_time: 5
  :use_object_ids: true
  :persist_types: false
  :option_no_exist: false

:test:
  <<: *defaults
  :name: whoops_test

:development:
  <<: *defaults
  :name: whoops_development
